# Generated by Django 2.1.13 on 2019-11-18 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='post-image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='reglogin',
            options={'verbose_name': 'Login', 'verbose_name_plural': 'Logins'},
        ),
        migrations.AddField(
            model_name='updatepost',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.RegLogin'),
        ),
    ]
