# Generated by Django 2.1.13 on 2019-11-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191118_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='login',
        ),
        migrations.RemoveField(
            model_name='updatepost',
            name='login',
        ),
        migrations.DeleteModel(
            name='RegLogin',
        ),
    ]
