# Generated by Django 2.1.13 on 2019-12-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191121_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='updatepost',
            name='imagen',
        ),
        migrations.AddField(
            model_name='updatepost',
            name='imagen0',
            field=models.ImageField(null=True, upload_to='post-image'),
        ),
        migrations.AddField(
            model_name='updatepost',
            name='imagen1',
            field=models.ImageField(null=True, upload_to='post-image'),
        ),
        migrations.AddField(
            model_name='updatepost',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='post-image'),
        ),
        migrations.AddField(
            model_name='consultar',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UpdatePost'),
        ),
    ]
